# 很多第三方组件的配置默认值一般均不需要改动，写在nacos 中比较混乱冗余，就可以写在此处

# sms4j配置
sms:
  is-print: false
  config-type: interface
sms-oa:
  config-type: yaml

# 行为验证码配置
aj:
  captcha:
    cache-type: redis

# 配置文件加密方法
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# liteflow配置
liteflow:
  rule-source: rules/*-rule.xml
  print-banner: false
  print-execution-log: false
  enable: true
